#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com IPs
echo "127.0.0.2 localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
