#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com IPs
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
if grep -q "facebook.com" /etc/hosts; then
    sed -i 's/.*facebook.com.*/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
